version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: pandas_nosetest
      - image: circleci/mysql:latest-ram
        environment:
          MYSQL_USER: "root"
          MYSQL_HOST: "localhost"
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: "pandas_nosetest"

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python test.py
